#!/usr/bin/env ruby

require 'optparse'
require 'optparse/time'

options = {}
OptionParser.new do |opts|
  opts.banner = "Usage: example.rb [options]"

  opts.on("-s", "--[no-]switch", "Run verbosely") do |v|
    options[:switch] = v
  end

  opts.on("-f", "--flag FLAG", "Run verbosely") do |f|
    options[:flag] = f
  end

  opts.on("-t", "--time TIME", Time, "Begin execution at given time") do |time|
    options[:time] = time
  end

  opts.on("-n", "--ndays NDAYS]", Integer, "Number of days until something") do |ndays|
    options[:ndays] = ndays
  end
end.parse!

p options
p ARGV

